---
packages:
  - htop
  - vim
  - tree
  - jq
  - curl
  - wget
  - zsh
  - flameshot
  - tilix
  - virtualbox
  - mlocate
  - apt-transport-https
  - python3-gpg
  - fonts-powerline


dell_drivers:
  - oem-somerville-melisa-meta 
  - libfprint-2-tod1-goodix 
  - oem-somerville-meta 
  - tlp-config


vscode_extensions:
  - ms-python.python
  - redhat.vscode-yaml
  - redhat.ansible
  - bbenoist.vagrant
  - dracula-theme.theme-dracula
  - pkief.material-icon-theme
  - kevinrose.vsc-python-indent
  - ms-vscode-remote.remote-ssh

...