---
packages:
  - apt-transport-https
  - bash-completion
  - curl
  - flameshot
  - fonts-powerline
  - htop
  - gnome-tweaks
  - jq
  - mlocate
  - python3-gpg
  - python3-pip
  - tilix
  - tree
  - vim
  - virtualbox
  - wget
  - zsh


dell_drivers:
  - libfprint-2-tod1-goodix 
  - oem-somerville-meta 
  - oem-somerville-melisa-meta
  - tlp-config


vscode_extensions:
  - bbenoist.vagrant
  - dracula-theme.theme-dracula
  - kevinrose.vsc-python-indent
  - ms-python.python
  - ms-vscode-remote.remote-ssh
  - pkief.material-icon-theme
  - redhat.ansible
  - redhat.vscode-yaml

...